# dsn
exp: "A2W+FULL+warm=6"
dataset: "office31"
data_transforms: None
data_loader_workers: 8
#* 从 student 网络上预训练出来保存好权重，然后加载 ； Pretrained on source
# pretrained: 'logs/TC_best_final_waugnoddisltcosaftepcheckpoint_bestin100eps_soep0_lr0.0002_bs32x32_gc16gd1gpl1_sd_0_atow.pt'
pretrained: 'logs/office31/warmup/130epoch_79.8acc_第30个 epoch 加入子网Warmup_s_resnet50_office31_a2w_lr=0.0002-2024-04-08_08:50:12_ckpt/best_a2w.pt'
# test pretrained resume
resume: ''
test_only: False
#source_domain
sdomain : "a"
source_path: "../DA_dataset/office31/amazon_list.txt"
#target_domain
tdomain : "w"
target_path: "../DA_dataset/office31/webcam_list.txt"

#model_scaling
model: "models.s_resnet"
depth: 50
num_subnets: 4
depth_mult_range: [0.5, 1]
depth_mult_list: [0.5, 1]
#？ 这里写着重置参数？难道就不需要加载参数了？
reset_parameters: True
width_mult_list: [0.9, 1]
width_mult_range: [0.9, 1]
resolution_list: [224, 192, 160, 128]
bit_width: [8,6,4]

#rd loss
warmup_teacher_temp: 0.04
teacher_temp: 0.04
warmup_teacher_temp_epochs: 0
ema_decay: 0.9


#loss_balancing
gamma_ce: 1
gamma_rd: 1
gamma_pl: 0.1
pl_thresh: 0.9


# 数据集图像信息
num_classes: 31
image_resize: 256
image_size: 224
#epochs
sonly_ep: 0
# 使用总训练 epoch 的10%作为 warmup
warm_ep: 6
warm_ep2: 6
num_epochs: 36
print_freq: 100
save_freq: 10

# optimizer
optimizer: "sgd"
momentum: 0.9
weight_decay: 0.001
nesterov: True

# lr
lr:   0.0002
lr_scheduler: "cosine"

# model profiling
profiling: ["gpu"]

#
random_seed: 50
############
#* 使用 ADV
use_discriminator: True
c_learning_rate: 0.0001
beta1: 0.9
beta2: 0.99

#* 这个损失是什么意思
use_iml: True
############
use_aug: True
is_cl_bln: False
lbl_smooth: True
s_bs: 32
t_bs: 32
batch_size: 32
log_dir: "logs/"